# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Check
      run: ./gradlew check
    - name: Test
      run: ./gradlew jacocoTestReport
    - name: Upload Codecov
      if: ${{ github.event_name == 'push' }}
      run: bash <(curl -s https://codecov.io/bash)
    - name: Build with Gradle
      run: ./gradlew build
    - name: Documentation
      run: ./gradlew javadoc
    - name: Deploy Action
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/docs/javadoc
